export const PRODUCTS_ACTION_TYPES = {
  FETCH_PRODUCTS_START: "PRODUCTS/FETCH_PRODUCTS_START",
  FETCH_PRODUCTS_SUCCESS: "PRODUCTS/FETCH_PRODUCTS_SUCCESS",
  FETCH_PRODUCTS_FAILED: "PRODUCTS/FETCH_PRODUCTS_FAILED",
  FETCH_PRODUCT_START: "PRODUCT/FETCH_PRODUCT_START",
  FETCH_PRODUCT_SUCCESS: "PRODUCT/FETCH_PRODUCT_SUCCESS",
  FETCH_PRODUCT_FAILED: "PRODUCT/FETCH_PRODUCT_FAILED",
};
