export const TRANSACTION_ACTION_TYPES = {
  TRANSACTION_BUY: "TRANSACTION/TRANSACTION_BUY",
  TRANSACTION_CONFIRM_OPEN: "TRANSACTION/TRANSACTION_CONFIRM_OPEN",
  TRANSACTION_CONFIRM_CLOSE: "TRANSACTION/TRANSACTION_CONFIRM_CLOSE",
  TRANSACTION_CONFIRM_START: "TRANSACTION/TRANSACTION_CONFIRM_START",
  TRANSACTION_CONFIRM_SUCCESS: "TRANSACTION/TRANSACTION_CONFIRM_SUCESS",
  TRANSACTION_CONFIRM_FAILED: "TRANSACTION/TRANSACTION_CONFIRM_FAILED",
  TRANSACTION_SET_FORM: "TRANSACTION/TRANSACTION_SET_FORM",
};
