export const ALLTRANSACTION_ACTION_TYPES = {
  ALLTRANSACTION_TRANSACTION_SAVE: "ALLTRANSACTION/ALLTRANSACTION_TRANSACTION_SAVE",
  ALLTRANSACTION_TRANSACTION_DELETE: "ALLTRANSACTION/ALLTRANSACTION_TRANSACTION_DELETE",
  ALLTRANSACTION_RATING_SET: "ALLTRANSACTION/ALLTRANSACTION_RATING_SET",
};
